apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: "POSTGRES_USER"
          value: "postgres"
        - name: "POSTGRES_PASSWORD"
          value: "Aw3s0m3"
        - name: "POSTGRES_DATABASE"
          value: "workshop"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /tmp/data
          name: postgres-data
      volumes:
      - name: postgres-data
        hostPath:
         path: /root/data
