apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: "POSTGRES_USER"
          value: "postgres"
        - name: "POSTGRES_PASSWORD"
          value: "Aw3s0m3"
        - name: "POSTGRES_DB"
          value: "WORKSHOP"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-config
          mountPath: /etc/config/initdb.sh
          subPath: initdb.sql
        - name: postgres-config
          mountPath: /etc/config/createTable.sql
          subPath: createTable.sql
      volumes:
      - name: postgres-config
        configMap:
         name: postgres-data
